relay_board_serial_port: /dev/ttyUSB0
# relay_board_serial_port: COM3
camera:
  relay: 0
  frame_rate_hz: 0.5
  start:
    year: 2016
    month: 4 # 1 <= month <= 12
    day: 18 # 1 <= day <= number of days in the given month and year
    hour: 16 # 0 <= hour < 24
    minute: 0 # 0 <= minute < 60
white_light:
  relay: 1
  pwm_on_duration_hours: 12
  pwm_off_duration_hours: 12
  pattern_on_duration_days: 3
  pattern_off_duration_days: 3
  start:
    year: 2016
    month: 4 # 1 <= month <= 12
    day: 18 # 1 <= day <= number of days in the given month and year
    hour: 16 # 0 <= hour < 24
    minute: 0 # 0 <= minute < 60
red_light:
  relay: 2
  pwm_frequency_hz: 10
  pwm_duty_cycle_percent: 50
  pattern_on_duration_hours: 12
  pattern_off_duration_hours: 12
  start:
    year: 2016
    month: 4 # 1 <= month <= 12
    day: 18 # 1 <= day <= number of days in the given month and year
    hour: 16 # 0 <= hour < 24
    minute: 0 # 0 <= minute < 60
board_indicator_light:
  relay: 7
