relay_board_serial_port_linux: /dev/ttyUSB0
relay_board_serial_port_windows: COM6
relay_board_serial_port_osx: /dev/tty.usbserial-11CP0195
camera:
  relay: 0
  frame_rate_hz: 0.5
  start:
    offset_days: 0 # -1 <= offset_days <= 10, -1 is start immediately, 0 is today, 1 is tomorrow, etc.
    hour: 16 # 0 <= hour < 24, 9 is 9AM, 16 is 4PM, etc.
    minute: 0 # 0 <= minute < 60, hour = 9 and minute = 0 is 9:00AM, hour = 16 and minute = 30 is 4:30PM, etc.
white_light:
  relay: 1
  pwm_on_duration_hours: 12
  pwm_off_duration_hours: 12
  pattern_on_duration_days: 3
  pattern_off_duration_days: 3
  power: 100 # 0 <= power <= 255, 0 is always off, 255 is always on
  start:
    offset_days: 0 # -1 <= offset_days <= 10, -1 is start immediately, 0 is today, 1 is tomorrow, etc.
    hour: 16 # 0 <= hour < 24, 9 is 9AM, 16 is 4PM, etc.
    minute: 0 # 0 <= minute < 60, hour = 9 and minute = 0 is 9:00AM, hour = 16 and minute = 30 is 4:30PM, etc.
red_light:
  relay: 2
  pwm_frequency_hz: 10
  pwm_duty_cycle_percent: 50
  pattern_on_duration_hours: 12
  pattern_off_duration_hours: 12
  start:
    offset_days: 0 # -1 <= offset_days <= 10, -1 is start immediately, 0 is today, 1 is tomorrow, etc.
    hour: 16 # 0 <= hour < 24, 9 is 9AM, 16 is 4PM, etc.
    minute: 0 # 0 <= minute < 60, hour = 9 and minute = 0 is 9:00AM, hour = 16 and minute = 30 is 4:30PM, etc.
board_indicator_light:
  relay: 7
